language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator_hexe_ruby_http' ]; then cd .. && eval "mv $currentfolder generator_hexe_ruby_http" && cd generator_hexe_ruby_http; fi
